"""
Django settings for django_rest project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import django_heroku

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'bzw!h#y!7%v-3g(b+l)7y_225c8*=5y24qx4$v1xfygl@%m2^r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

#keycloak configuration
KEYCLOAK_BEARER_AUTHENTICATION_EXEMPT_PATHS = [
    'admin', 'accounts',
    ]


KEYCLOAK_CONFIG = {
    'KEYCLOAK_SERVER_URL': 'https://keycloak-test.tk/auth/',
    'KEYCLOAK_REALM': 'first-auth',
    'KEYCLOAK_CLIENT_ID': 'app-first-auth',
    'KEYCLOAK_CLIENT_SECRET_KEY': '36865bf0-a8c8-4bcd-96cb-f4994b92bf05',
    'KEYCLOAK_DEFAULT_ACCESS': 'DENY', # DENY or ALLOW (Default is DENY)
    'KEYCLOAK_AUTHORIZATION_CONFIG': os.path.join(BASE_DIR,  'app-first-auth-authz-config.json'),
    'KEYCLOAK_METHOD_VALIDATE_TOKEN': 'INTROSPECT', # INTROSPECT OR DECODE (Default is INTROSPECT)
}

# cors headers

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
ALLOWED_HOSTS = ['*']

#swagger

SWAGGER_SETTINGS = {
    # 'SECURITY_DEFINITIONS': {
    #     'oauth2': {
    #         'type': 'oauth2',
    #         'description': 'test',
    #         "flow": "password",
    #         "authorizationUrl": "http://localhost:8081/auth/realms/first-auth/protocol/openid-connect/auth",
    #         "tokenUrl": "http://localhost:8081/auth/realms/first-auth/protocol/openid-connect/token",
    #         # "scopes": {
    #         #         "product:add": "Adicionar produto",
    #         #         "product:delete": "Eliminar produto",
    #         #         "product:update": "Editar produto",
    #         #         "product:list": "Listar Produtos"
    #         # },
    #         "client_id": "app-first-auth",
    #         "client_secret": "045543e3-bea7-4ace-ac31-3e0edefdecc7",
    #     }
    # },
    # "SHOW_REQUEST_HEADERS": True,
    # 'CUSTOM_HEADERS': {
    #     "realm": "first-auth"
    # }

    'SECURITY_DEFINITIONS': {
        'bearerAuth': {            
            'type': 'apiKey',
            "name": "Authorization",
            "in": "header",
            'scheme': 'bearer',
            'bearerFormat': 'JWT',
        },
    }
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'django_keycloak',
    'corsheaders',
    'rest_framework_swagger',
    'drf_yasg',

    'products',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_rest.middleware.django_keycloak_middleware.KeycloakMiddleware',
]

ROOT_URLCONF = 'django_rest.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_rest.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # },
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'django-rest',
        'USER': 'django-rest',
        'PASSWORD': 'django-rest',
        'HOST': 'localhost',
        'PORT': '5432',
    },
    
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

django_heroku.settings(locals())
